### ISSUE TITLE
reference to missing repo: git@github.com:mattmc3/secrets

### ISSUE THREAD

**Issue by dv99156** [mattmc3/zdotdir#2]
[plugins/otp/otp.plugin.zsh](https://github.com/mattmc3/zdotdir/blob/0ba009a669ba524f93bd2981cbfa70fd9edfa3a2/plugins/otp/otp.plugin.zsh#L15)
 git@github.com:mattmc3/secrets

**Comment by mattmc3** [comment]
That’s my private repo for my secrets. I’m not opening that up to anyone.
